# 这个 workflow 配置用于控制 GitHub Actions 的自动打卡
# 如果有需要，请按照注释的提示，修改内容

name: XMU daily health report

on:
  push:
    branches: [ $default-branch ]
  schedule:
    - cron: "05 0,2,4 * * *"             # 执行打卡任务的时间，默认是 8:05，需要将其转换成 UTC+0 时区（即比北京时间晚 8 小时），所以 8:05 => 0:05
    # 请注意，由于本程序需要根据日期字符串获取每日的打卡表单，而 GitHub Action 的服务器具有时差，因此如果上面的 Cron 填写在北京时间 8 点（UTC 时间 0 点）之前，会导致打卡失败，
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        node-version: 12.x
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: random sleep
      uses: m3y/random-wait-action@v1
      with:
        max-wait-time: 3600
    - name: running check in
      run: |
          python workflow.py
      env:
        REPORT_XMU_USERNAME: ${{ secrets.xmu_username }}
        REPORT_XMU_PASSWORD: ${{ secrets.xmu_password }}
        REPORT_VPN_USERNAME: ${{ secrets.vpn_username }}
        REPORT_VPN_PASSWORD: ${{ secrets.vpn_password }}
        REPORT_USE_VPN: true
        # REPORT_REPORT_TYPE: server_chan # 选择打卡提醒的方式，默认为 Server 酱，可选钉钉
        # REPORT_SERVER_CHAN_SECRET: ${{ secrets.server_chan_secret }}    # 如果你不需要通过 Server 酱 (http://sc.ftqq.com/) 进行打卡结果提醒，请注释此行
        # 注意修改者使用的是钉钉，所以如果需要使用Server 酱，请取消以上两行的注释，并注释以下三行
        REPORT_REPORT_TYPE: dingtalk
        REPORT_DINGTALK_WEBHOOK: ${{ secrets.dingtalk_webhook }}
        REPORT_DINGTALK_SECRET: ${{ secrets.dingtalk_secret }}
